---
title: "Mentoring Efficiency - IR Centers 2"
author: "Nicholas Kaufman"
date: "2025-06-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, root.dir = "Users/nickkaufman/downloads")
library(readxl)
library(binom)
library(ggplot2)
library(devtools)
library(fANCOVA)
library(plotly)
library(dplyr)
library(tidyr)
library(corrplot)
library(lubridate)
library(patchwork)
library(effectsize)
library(Matrix)
library(mgcv)
library(ggpubr)
library(gratia) 
library(scales)
library(plotly)
```

```{r}
Data <- read_excel("Downloads/Mentoring Efficiency.xlsx", 
col_types = c("text", "text", "date", 
"numeric", "numeric", "skip", "skip", 
"skip"))

colnames(Data) <- c("Site", "Patient_Last_Name", "Procedure_Date", 
"Fluoroscopy_Time", "Radiation_Dose")

Data <- Data %>%
  mutate(Site = ifelse(Site == "St. Louis", "St.Louis", Site))


 Data <- Data[-c(106, 162, 176, 1287), ]
 Data <- Data[order(Data$Site, Data$Procedure_Date), ]
 Data$Month <- format(Data$Procedure_Date, "%B %Y")
 
Data <- Data %>%
  mutate(Month_Date = floor_date(Procedure_Date, unit = "month"),
         Month = format(Month_Date, "%B %Y")) 
Data <- Data %>%
  mutate(Site = factor(Site),
         Month = factor(Month, levels = unique(Month[order(Month_Date)])))

```

```{r}
Data.Filtered <- Data %>% filter(Fluoroscopy_Time >= 15)

Data <- Data %>%
mutate(Procedure_Date = as.Date(Procedure_Date))

weekly_avgs <- Data.Filtered %>%
  mutate(Week = floor_date(Procedure_Date, unit = "week", week_start = 1)) %>%
  group_by(Site, Week) %>%
  summarise(Avg_Fluoro_Time = mean(Fluoroscopy_Time, na.rm = TRUE), 
            .groups = "drop")

```

```{r}
plots <- function(site_name) {
  fxn <- weekly_avgs %>% filter(Site == site_name)
  fxn$Week <- as.Date(fxn$Week) 
  
  
fxn <- fxn %>%
mutate(tooltip_text = paste0("Week: ", format(Week, "%Y-%m-%d"),
         "<br>Avg Fluoro Time: ", round(Avg_Fluoro_Time, 2)))
  plot_fxn <- ggplot(fxn, aes(x = Week, y = Avg_Fluoro_Time)) +
    geom_line(color = "black", show.legend = FALSE) +
    geom_point(aes(color = "Weekly Average",
                   text = paste0("Week: ", format(Week, "%Y-%m-%d"), 
"<br>Avg Fluoro Time: ", round(Avg_Fluoro_Time, 2))),
               size = 2) +
    geom_smooth(aes(color = "Smoothed Trend"), se = FALSE, method = "loess") +
    geom_smooth(aes(color = "Linear Trend"), se = FALSE, method = "lm") +
    scale_color_manual(
      name = "Legend",
      values = c(
        "Weekly Average" = "red",
        "Smoothed Trend" = "blue",
        "Linear Trend" = "green"
      )
    ) +
    scale_x_date(
      date_breaks = "4 weeks",
      date_labels = "%Y-%m-%d"
    ) +
    labs(title = paste("Weekly Average Fluoroscopy Time -", site_name),
         x = "Week",
         y = "Average Fluoroscopy Time (min)") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "bottom"
    )
  
  ggplotly(plot_fxn, tooltip = "text") 

}

plots("Arizona")
plots("Louisville")
plots("St.Louis")
plots("Syracuse/AMP")
plots("Wilmington")


```

```{r}

plots1 <- function(site_name) {
  fxn1 <- weekly_avgs %>% filter(Site == site_name)
  fxn1$Week <- as.Date(fxn1$Week) 
  
fxn1 <- fxn1 %>%
mutate(tooltip_text = paste0("Week: ", format(Week, "%Y-%m-%d"),
                                 "<br>Avg Fluoro Time: ",
                             round(Avg_Fluoro_Time, 2)))
  
  plot_fxn1 <- ggplot(fxn1, aes(x = Week, y = Avg_Fluoro_Time)) +
    geom_line(color = "black", show.legend = FALSE) +
    geom_point(aes(color = "Weekly Average",
                  text = paste0("Week: ", format(Week, "%Y-%m-%d"), 
   "<br>Avg Fluoro Time: ", round(Avg_Fluoro_Time, 2))),
               size = 2) +
    geom_smooth(aes(color = "Linear Trend"), se = FALSE, method = "lm") +
    scale_color_manual(
      name = "Legend",
      values = c(
        "Weekly Average" = "red",
        "Linear Trend" = "green"
      )
    ) +
    scale_x_date(
      date_breaks = "4 weeks",
      date_labels = "%Y-%m-%d"
    ) +
    labs(title = paste("Weekly Average Fluoroscopy Time -", site_name),
         x = "Week",
         y = "Average Fluoroscopy Time (min)") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "bottom"
    )
  
  ggplotly(plot_fxn1, tooltip = "text")
}


plots1("Arizona")
plots1("Louisville")
plots1("St.Louis")
plots1("Syracuse/AMP")
plots1("Wilmington")

```

```{r}
plots2 <- function(site_name) {
  fxn2 <- weekly_avgs %>% filter(Site == site_name)
  fxn2$Week <- as.Date(fxn2$Week) 
  
fxn2 <- fxn2 %>%
mutate(tooltip_text = paste0("Week: ", format(Week, "%Y-%m-%d"),
                                 "<br>Avg Fluoro Time: ",
                             round(Avg_Fluoro_Time, 2)))
  
  
  plot_fxn2 <- ggplot(fxn2, aes(x = Week, y = Avg_Fluoro_Time)) +
    geom_line(color = "black", show.legend = FALSE) +
    geom_point(aes(color = "Weekly Average",
                   text = paste0("Week: ", format(Week, "%Y-%m-%d"),
 "<br>Avg Fluoro Time: ", round(Avg_Fluoro_Time, 2))),
               size = 2) +
    geom_smooth(aes(color = "Smoothed Trend"), se = FALSE, method = "loess") +
    scale_color_manual(
      name = "Legend",
      values = c(
        "Weekly Average" = "red",
        "Smoothed Trend" = "blue"
      )
    ) +
    scale_x_date(
      date_breaks = "4 weeks",
      date_labels = "%Y-%m-%d"
    ) +
    labs(title = paste("Weekly Average Fluoroscopy Time -", site_name),
         x = "Week",
         y = "Average Fluoroscopy Time (min)") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "bottom"
    )
  
  ggplotly(plot_fxn2, tooltip = "text")
}

plots2("Arizona")
plots2("Louisville")
plots2("St.Louis")
plots2("Syracuse/AMP")
plots2("Wilmington")







```